{print} = require 'sys'
{spawn} = require 'child_process'

task 'sbuild', 'Build lib/ from src/', ->
	coffee = spawn 'coffee', ['-c', '-o', 'lib', 'src']
	print "Building test with #{coffee}"
	
	coffee.stderr.on 'data', (data) ->
    	process.stderr.write data.toString()
