// Generated by CoffeeScript 1.6.3
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["studiogdo/listAndSelection"], function(ListSelection) {
  var ListOrSelection;
  return ListOrSelection = (function(_super) {
    __extends(ListOrSelection, _super);

    function ListOrSelection() {
      this.showListBOCallback = __bind(this.showListBOCallback, this);
      this.showSelectedBOCallback = __bind(this.showSelectedBOCallback, this);
      this.closeSelectedCallback = __bind(this.closeSelectedCallback, this);
      ListOrSelection.__super__.constructor.apply(this, arguments);
    }

    ListOrSelection.prototype.closeSelectedCallback = function(evt) {
      ListOrSelection.__super__.closeSelectedCallback.apply(this, arguments);
      return $(this.list).show();
    };

    ListOrSelection.prototype.showSelectedBOCallback = function() {
      ListOrSelection.__super__.showSelectedBOCallback.apply(this, arguments);
      return $(this.list).hide();
    };

    ListOrSelection.prototype.showListBOCallback = function(bocall) {
      ListOrSelection.__super__.showListBOCallback.apply(this, arguments);
      return $(this.list).show();
    };

    return ListOrSelection;

  })(ListSelection);
});

/*
//@ sourceMappingURL=listOrSelection.map
*/
